### ISSUE TITLE
could not download https://charts.helm.sh/stable/mysql-1.6.9.tgz:

### ISSUE THREAD

**Issue by arnaudbagnis** [vuongxuongminh/docker-helm-symfony#11]
[node1 docker-helm-symfony]$ helm dep update ./helm/symfony
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
...Successfully got an update from the "https://kubernetes-charts.storage.googleapis.com" chart repository
Saving 2 charts
Downloading mysql from repo https://kubernetes-charts.storage.googleapis.com
Save error occurred:  could not download https://charts.helm.sh/stable/mysql-1.6.9.tgz: failed to fetch https://charts.helm.sh/stable/mysql-1.6.9.tgz : 404 Not Found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://charts.helm.sh/stable/mysql-1.6.9.tgz: failed to fetch https://charts.helm.sh/stable/mysql-1.6.9.tgz : 404 Not Found

**Comment by vuongxuongminh** [comment]
Fixed, please re-download `v2.1.1` and try again.
